name: "goods_web"
webPort: 8022
webHost: "172.16.3.176"
goods_srv: 
  host: "172.16.3.176"
  port: 50051
  name: "goods_srv"
mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123123"

jwt:
  key: "!D2IQQkifrjWh$N9YpnH^9MeFtFoCTFH"


consul:
  host: "172.16.3.176"
  port: 8500
